name: Unit Tests

on: [push, pull_request]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-modules-${ hashFiles('**/yarn.lock')}

      - name: Run Tests
        run: |
          yarn
          yarn test
